---
title: "Untitled"
author: "Arne Diedrich"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
library(stargazer)
```
```{r Importing Regerssion,code = readLines("FE-Regression.R"), include=FALSE}

```

### Pooled Models
```{r pooled, echo=FALSE, fig.width=20, results='asis'}
stargazer(LIB_pooled, EGAL_pooled, PART_pooled, DELIB_pooled, POLY_pooled, 
          type = "html",
          dep.var.caption = "V-Dem Component Indices:",
          star.char = c(".", "*", "**", "***"),
          star.cutoffs = c(0.1, 0.05, 0.01, 0.001),
          decimal.mark = ",",
          digit.separator = ".",
          notes.label = "Legende:",
          notes.append = FALSE,
          notes = ".p<0,1; *p<0,05; **p<0,01; ***p<0,001",
          add.lines = list(c("Fixed Effects: Land", "nein", "nein", "nein", "nein", "nein"), 
                           c("Fixed Effects: Jahr", "nein", "nein", "nein", "nein", "nein")))

```

### Fixed Effects Models
```{r Fe_Year, echo=FALSE}
stargazer(LIB_fe_y, EGAL_fe_y, PART_fe_y, DELIB_fe_y, POLY_fe_y, 
          type = "text", 
          omit = names(table(df_LD$year)),
          dep.var.caption = "V-Dem Component Indices:",
          star.char = c(".", "*", "**", "***"),
          star.cutoffs = c(0.1, 0.05, 0.01, 0.001),
          decimal.mark = ",",
          digit.separator = ".",
          notes.label = "Legende:",
          notes.append = FALSE,
          notes = ".p<0,1; *p<0,05; **p<0,01; ***p<0,001",
          add.lines = list(c("Fixed Effects: Land", "nein", "nein", "nein", "nein", "nein"), 
                           c("Fixed Effects: Jahr", "ja", "ja", "ja", "ja", "ja"))
          )
```
```{r Fe_Country, echo=FALSE}
stargazer(LIB_fe_c, EGAL_fe_c, PART_fe_c, DELIB_fe_c, POLY_fe_c, 
          type = "text", 
          omit = names(table(df_LD$country_name)),
          dep.var.caption = "V-Dem Component Indices:",
          star.char = c(".", "*", "**", "***"),
          star.cutoffs = c(0.1, 0.05, 0.01, 0.001),
          decimal.mark = ",",
          digit.separator = ".",
          notes.label = "Legende:",
          notes.append = FALSE,
          notes = ".p<0,1; *p<0,05; **p<0,01; ***p<0,001",
          add.lines = list(c("Fixed Effects: Land", "ja", "ja", "ja", "ja", "ja"), 
                           c("Fixed Effects: Jahr", "nein", "nein", "nein", "nein", "nein"))
          )
```
```{r Fe_Year_Country, echo=FALSE}
stargazer(LIB_fe_c_y, EGAL_fe_c_y, PART_fe_c_y, DELIB_fe_c_y, POLY_fe_c_y, 
          type = "text", 
          omit = c(names(table(df_LD$country_name)), names(table(df_LD$year))),
          dep.var.caption = "V-Dem Component Indices:",
          star.char = c(".", "*", "**", "***"),
          star.cutoffs = c(0.1, 0.05, 0.01, 0.001),
          decimal.mark = ",",
          digit.separator = ".",
          notes.label = "Legende:",
          notes.append = FALSE,
          notes = ".p<0,1; *p<0,05; **p<0,01; ***p<0,001",
          add.lines = list(c("Fixed Effects: Land", "ja", "ja", "ja", "ja", "ja"), 
                           c("Fixed Effects: Jahr", "ja", "ja", "ja", "ja", "ja"))
)
```